In [2]:
import numpy as np

import pandas as pd

#creaton series
s = pd.Series([1, 2, 3, 'ad', 3, np.nan])
s

0      1
1      2
2      3
3     ad
4      3
5    NaN
dtype: object

In [104]:
#creating DataFrame
dates = pd.date_range('20130101', periods=6)
dates[1]

arr = np.random.randn(6, 4)

df = pd.DataFrame(arr, index=dates, columns=list('ABCD'))

print(df)
print('\n')
print(arr)


                   A         B         C         D
2013-01-01  0.328548  0.452415  1.004055 -0.366403
2013-01-02  2.246330  0.620248 -1.267600 -0.028922
2013-01-03 -1.219712 -1.418529 -0.718819 -0.385020
2013-01-04 -0.816584 -0.443397 -0.412879  1.203345
2013-01-05 -1.090148  0.926962 -0.121889 -1.191289
2013-01-06  0.842420  0.155791  0.117149  1.600828


[[ 0.32854758  0.45241511  1.00405488 -0.3664033 ]
 [ 2.24633041  0.62024808 -1.26759982 -0.02892201]
 [-1.21971185 -1.41852945 -0.71881861 -0.38502048]
 [-0.8165839  -0.44339665 -0.41287899  1.20334491]
 [-1.09014801  0.92696183 -0.12188911 -1.19128916]
 [ 0.84242     0.15579051  0.11714855  1.60082798]]


In [ ]:
df2 = pd.DataFrame({ 'A': 1.,
                    'B': pd.Timestamp('20130102'),
                    'C': pd.Series(1, index=list(range(4)),  dtype='float32'),
                    'D': np.array([3] * 4, dtype='int32'),
                    'E': pd.Categorical(["test", "train", "test", "train"]),
                    'F': 'foo' })

print(df2)
df2.dtypes


In [21]:
df2.bool
#?????

<bound method NDFrame.bool of      A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo>

In [54]:
df2.index
print(df2.index)
print(df2.columns)

Int64Index([0, 1, 2, 3], dtype='int64')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')


In [66]:

print(df.to_numpy(), '\n')
print(df2.to_numpy())
print('\n')
print(df.T)

[[ 0.6032665  -0.30680373  1.04752604  1.01139537]
 [-1.15556476  2.19935779  0.48415873  0.34060081]
 [-1.52512485 -1.35054179  0.1795713   0.57894288]
 [-1.80285745 -1.63013592  0.2541295   0.79628418]
 [-1.24507426 -3.22389845 -0.32974278 -0.71804825]
 [ 2.2827239  -2.34253151 -1.10221432 -1.22875152]] 

[[1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'test' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'train' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'test' 'foo']
 [1.0 Timestamp('2013-01-02 00:00:00') 1.0 3 'train' 'foo']]


   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.603267   -1.155565   -1.525125   -1.802857   -1.245074    2.282724
B   -0.306804    2.199358   -1.350542   -1.630136   -3.223898   -2.342532
C    1.047526    0.484159    0.179571    0.254129   -0.329743   -1.102214
D    1.011395    0.340601    0.578943    0.796284   -0.718048   -1.228752


In [65]:
print(df.describe())

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.473772 -1.109092  0.088905  0.130071
std    1.593100  1.892779  0.735490  0.898007
min   -1.802857 -3.223898 -1.102214 -1.228752
25%   -1.455112 -2.164433 -0.202414 -0.453386
50%   -1.200320 -1.490339  0.216850  0.459772
75%    0.163559 -0.567738  0.426651  0.741949
max    2.282724  2.199358  1.047526  1.011395


   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.603267   -1.155565   -1.525125   -1.802857   -1.245074    2.282724
B   -0.306804    2.199358   -1.350542   -1.630136   -3.223898   -2.342532
C    1.047526    0.484159    0.179571    0.254129   -0.329743   -1.102214
D    1.011395    0.340601    0.578943    0.796284   -0.718048   -1.228752


In [68]:
print(df.sort_values(by='B'))

                   A         B         C         D
2013-01-05 -1.245074 -3.223898 -0.329743 -0.718048
2013-01-06  2.282724 -2.342532 -1.102214 -1.228752
2013-01-04 -1.802857 -1.630136  0.254129  0.796284
2013-01-03 -1.525125 -1.350542  0.179571  0.578943
2013-01-01  0.603267 -0.306804  1.047526  1.011395
2013-01-02 -1.155565  2.199358  0.484159  0.340601


In [69]:
ser = pd.Series(df['A'])
print(ser)

2013-01-01    0.603267
2013-01-02   -1.155565
2013-01-03   -1.525125
2013-01-04   -1.802857
2013-01-05   -1.245074
2013-01-06    2.282724
Freq: D, Name: A, dtype: float64


In [84]:
print(df[0:2])
print(df['20130102':'20130104'])

                   A         B         C         D
2013-01-01  0.603267 -0.306804  1.047526  1.011395
2013-01-02 -1.155565  2.199358  0.484159  0.340601
                   A         B         C         D
2013-01-02 -1.155565  2.199358  0.484159  0.340601
2013-01-03 -1.525125 -1.350542  0.179571  0.578943
2013-01-04 -1.802857 -1.630136  0.254129  0.796284


In [106]:
print(df.loc['20130102'])

A    2.246330
B    0.620248
C   -1.267600
D   -0.028922
Name: 2013-01-02 00:00:00, dtype: float64


In [99]:
print(df2.loc[:, ['A', 'B']])

     A          B
0  1.0 2013-01-02
1  1.0 2013-01-02
2  1.0 2013-01-02
3  1.0 2013-01-02


In [112]:
print(df.iloc[0:2], '\n')

print(df.iloc[3:5, 0:2])

                   A         B         C         D
2013-01-01  0.328548  0.452415  1.004055 -0.366403
2013-01-02  2.246330  0.620248 -1.267600 -0.028922 

                   A         B
2013-01-04 -0.816584 -0.443397
2013-01-05 -1.090148  0.926962


In [114]:
print(df.iloc[1:3, :])

                   A         B         C         D
2013-01-02  2.246330  0.620248 -1.267600 -0.028922
2013-01-03 -1.219712 -1.418529 -0.718819 -0.385020


In [115]:
print(df.iat[1, 1])

0.6202480755622647


In [120]:
print(df[df.A > 0])


                   A         B         C         D
2013-01-01  0.328548  0.452415  1.004055 -0.366403
2013-01-02  2.246330  0.620248 -1.267600 -0.028922
2013-01-06  0.842420  0.155791  0.117149  1.600828


In [136]:
print(df2[df2.E.isin(['test'])])
# df.iat[0, 1] = 0  --set location

     A          B    C  D     E    F
0  1.0 2013-01-02  1.0  3  test  foo
2  1.0 2013-01-02  1.0  3  test  foo


In [155]:
df[df < 0] = -df
print(df)

                   A         B         C         D
2013-01-01  0.164274  0.226208  0.502027  0.183202
2013-01-02  1.123165  0.310124  0.633800  0.014461
2013-01-03  0.609856  0.709265  0.359409  0.192510
2013-01-04  0.408292  0.221698  0.206439  0.601672
2013-01-05  0.545074  0.463481  0.060945  0.595645
2013-01-06  0.421210  0.077895  0.058574  0.800414


In [4]:
df.dropna(how='any') #drop missing data (NaN)
df.fillna(value=5) #fill missing data (NaN)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>A</th>
      <th>B</th>
      <th>C</th>
      <th>D</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>-0.260710</td>
      <td>2.012426</td>
      <td>-0.983352</td>
      <td>-0.840761</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0.016985</td>
      <td>0.472143</td>
      <td>-0.452083</td>
      <td>-0.553454</td>
    </tr>
    <tr>
      <th>2</th>
      <td>-0.797740</td>
      <td>-0.932179</td>
      <td>-0.120345</td>
      <td>-0.469060</td>
    </tr>
    <tr>
      <th>3</th>
      <td>-0.260398</td>
      <td>-1.234067</td>
      <td>0.984015</td>
      <td>-0.533827</td>
    </tr>
    <tr>
      <th>4</th>
      <td>-1.535116</td>
      <td>0.775688</td>
      <td>1.215256</td>
      <td>-3.389297</td>
    </tr>
    <tr>
      <th>5</th>
      <td>0.912181</td>
      <td>0.971262</td>
      <td>1.349575</td>
      <td>1.754676</td>
    </tr>
    <tr>
      <th>6</th>
      <td>-2.558229</td>
      <td>0.758910</td>
      <td>-0.055621</td>
      <td>0.658454</td>
    </tr>
    <tr>
      <th>7</th>
      <td>-0.940878</td>
      <td>0.494694</td>
      <td>0.775775</td>
      <td>0.385695</td>
    </tr>
  </tbody>
</table>
</div>

In [3]:
df = pd.DataFrame(np.random.randn(8, 4), columns=['A', 'B', 'C', 'D'])
print(df)

          A         B         C         D
0 -0.260710  2.012426 -0.983352 -0.840761
1  0.016985  0.472143 -0.452083 -0.553454
2 -0.797740 -0.932179 -0.120345 -0.469060
3 -0.260398 -1.234067  0.984015 -0.533827
4 -1.535116  0.775688  1.215256 -3.389297
5  0.912181  0.971262  1.349575  1.754676
6 -2.558229  0.758910 -0.055621  0.658454
7 -0.940878  0.494694  0.775775  0.385695


In [7]:
s = df.iloc[3]

df.append(s, ignore_index=True)

print(df)

     A      B         C         D
0  foo    one -0.236809 -1.876826
1  bar    one -1.071322 -2.496502
2  foo    two  1.403935  2.369630
3  bar  three -1.346662 -1.854155
4  foo    two -0.760024  0.653604
5  bar    two -1.365279 -0.527546
6  foo    one  0.030875 -0.481934
7  foo  three  0.073679  0.356013


In [6]:
df = pd.DataFrame({'A': ['foo', 'bar', 'foo', 'bar',
                         'foo', 'bar', 'foo', 'foo'],
                   'B': ['one', 'one', 'two', 'three',
                         'two', 'two', 'one', 'three'],
                   'C': np.random.randn(8),
                   'D': np.random.randn(8)})
print(df.groupby('A').sum())

            C         D
A                      
bar -3.783262 -4.878203
foo  0.511656  1.020487


In [13]:
print(df.groupby('A').sum())

            C         D
A                      
bar -3.783262 -4.878203
foo  0.511656  1.020487


In [14]:
print(df.groupby(['A', 'B']).sum())

                  C         D
A   B                        
bar one   -1.071322 -2.496502
    three -1.346662 -1.854155
    two   -1.365279 -0.527546
foo one   -0.205934 -2.358760
    three  0.073679  0.356013
    two    0.643911  3.023234


In [16]:
print(df.groupby(['A', 'B']).sum())

                  C         D
A   B                        
bar one   -1.071322 -2.496502
    three -1.346662 -1.854155
    two   -1.365279 -0.527546
foo one   -0.205934 -2.358760
    three  0.073679  0.356013
    two    0.643911  3.023234


In [20]:
tuples = list(zip(*[['bar', 'bar', 'baz', 'baz',
                     'foo', 'foo', 'qux', 'qux'],
                    ['one', 'two', 'one', 'two',
                     'one', 'two', 'one', 'two']]))

index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=['A', 'B'])
print(df)


                     A         B
first second                    
bar   one     0.281499  0.373480
      two    -0.747074  1.137719
baz   one    -1.298807  1.252030
      two     1.370114 -1.038226
foo   one     0.429620 -0.738014
      two     0.312051 -1.274835
qux   one    -0.442799  0.629779
      two    -0.995176  1.047575


In [22]:
print(df.stack())  # make 2d for 'A' and 'B'  unstack()


first  second   
bar    one     A    0.281499
               B    0.373480
       two     A   -0.747074
               B    1.137719
baz    one     A   -1.298807
               B    1.252030
       two     A    1.370114
               B   -1.038226
foo    one     A    0.429620
               B   -0.738014
       two     A    0.312051
               B   -1.274835
qux    one     A   -0.442799
               B    0.629779
       two     A   -0.995176
               B    1.047575
dtype: float64


In [31]:
rng = pd.date_range('1/1/2012', periods=100, freq='S')

ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

print(ts.head(10))

print(ts.resample('1Min').sum())

2012-01-01 00:00:00     23
2012-01-01 00:00:01    337
2012-01-01 00:00:02    345
2012-01-01 00:00:03    285
2012-01-01 00:00:04    175
2012-01-01 00:00:05      1
2012-01-01 00:00:06     98
2012-01-01 00:00:07    418
2012-01-01 00:00:08    449
2012-01-01 00:00:09    173
Freq: S, dtype: int32
2012-01-01 00:00:00    12942
2012-01-01 00:01:00     9873
Freq: T, dtype: int32


In [32]:
rng = pd.date_range('3/6/2012 00:00', periods=5, freq='D')

ts = pd.Series(np.random.randn(len(rng)), rng)

ts_utc = ts.tz_localize('UTC')

print(ts_utc)

2012-03-06 00:00:00+00:00    0.867166
2012-03-07 00:00:00+00:00    0.364536
2012-03-08 00:00:00+00:00   -0.872213
2012-03-09 00:00:00+00:00   -0.741548
2012-03-10 00:00:00+00:00    2.121447
Freq: D, dtype: float64


In [35]:
ts_utc.tz_convert('US/Eastern')

2012-03-05 19:00:00-05:00    0.867166
2012-03-06 19:00:00-05:00    0.364536
2012-03-07 19:00:00-05:00   -0.872213
2012-03-08 19:00:00-05:00   -0.741548
2012-03-09 19:00:00-05:00    2.121447
Freq: D, dtype: float64